---
- name: Initialize local environment for Ansible controller
  hosts: localhost
  gather_facts: false
  connection: local
  remote_user: demo
  become: true
  become_method: su
  become_user: root
  vars:
    packages:
      - bash-completion
      - vim
      - curl
      - wget
      - sshpass
      - git
      - python3
      - resolvconf
      - apt-transport-https
      - ca-certificates
      - ansible
      - ansible-lint
      - python3-ansible-runner
      - python3-typer
    network:
      interface: ens33
      ipaddress: 192.168.132.101/24
      gateway: 192.168.132.2
      dns:
        - 192.168.132.2
        - 223.5.5.5
      search: example.com
    hostname: ansible-controller
  roles:
    - system_init
